#!/usr/bin/env python3
"""firing_percent_latex_tables.py

Aggregate one or more firing_percent runs into two booktabs-style LaTeX
snippets suitable for paper/thesis inclusion.

Outputs:
  <output_dir>/summary_table.tex
    Rows = labeled scopes/modes; cols = N points, avg firing rate (%),
    recommended tau, % points >=1/>=2/>=5/>=10 at the recommended tau.

  <output_dir>/sweep_table.tex
    Rows = tau (subset chosen via --tau_subset); top-level multi-column
    header per scope/mode; sub-cols = >=1% >=2% >=5% >=10%.

Both files are self-contained `tabular` environments — paste inside your
own \\begin{table} with your preferred caption.

Required LaTeX packages: booktabs, optionally siunitx for \\num{}.

Inputs are passed as positional `LABEL=PATH` pairs via `--inputs`. PATH
points to a `firing_percent` directory (the one containing data/ and
plots/), e.g.:

  raw=results/_genome_wide/sae_tsne/.../firing_percent
  prenorm=results/_genome_wide/sae_tsne_prenorm/.../firing_percent
  postnorm=results/_genome_wide/sae_tsne_postnorm/.../firing_percent
"""

import argparse
import json
import logging
import os
import sys
from collections import OrderedDict

import pandas as pd

logger = logging.getLogger(__name__)

DEFAULT_TAU_SUBSET = [0.0, 1.0, 2.0, 3.0, 5.0, 7.0, 10.0]
BUCKET_COLUMNS = ["pct_points_ge1pct", "pct_points_ge2pct",
                  "pct_points_ge5pct", "pct_points_ge10pct"]
BUCKET_HEADERS = [r"$\geq$1\%", r"$\geq$2\%", r"$\geq$5\%", r"$\geq$10\%"]


def setup_logging(level="INFO"):
    logging.basicConfig(
        level=level,
        format="[%(asctime)s] %(levelname)s %(message)s",
        datefmt="%H:%M:%S",
    )


def parse_args():
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--inputs", required=True, nargs="+",
                   help="LABEL=PATH pairs, one per scope/mode to compare. "
                        "PATH points to a firing_percent directory.")
    p.add_argument("--output_dir", required=True,
                   help="Directory to write summary_table.tex and sweep_table.tex")
    p.add_argument("--tau_subset",
                   default=",".join(f"{t:g}" for t in DEFAULT_TAU_SUBSET),
                   help="Comma-separated tau values to include in the sweep table")
    p.add_argument("--use_siunitx", action="store_true",
                   help="Format numbers with \\num{} from siunitx (default: plain)")
    p.add_argument("--log_level", default="INFO")
    return p.parse_args()


def parse_inputs(pairs):
    out = OrderedDict()
    for s in pairs:
        if "=" not in s:
            raise ValueError(f"Bad --inputs entry {s!r}: expected LABEL=PATH")
        label, path = s.split("=", 1)
        label = label.strip()
        path = path.strip()
        if not os.path.isdir(path):
            raise FileNotFoundError(f"Input dir not found: {path}")
        out[label] = path
    return out


def load_run(path):
    summary_path = os.path.join(path, "data", "summary.json")
    sweep_path = os.path.join(path, "data", "firing_sweep.tsv")
    if not os.path.isfile(summary_path):
        raise FileNotFoundError(summary_path)
    if not os.path.isfile(sweep_path):
        raise FileNotFoundError(sweep_path)
    with open(summary_path) as f:
        summary = json.load(f)
    sweep = pd.read_csv(sweep_path, sep="\t")
    return summary, sweep


def fmt_int(n, use_siunitx):
    if use_siunitx:
        return rf"\num{{{int(n)}}}"
    return f"{int(n):,}".replace(",", r"\,")


def fmt_pct(x, decimals=2):
    if x is None:
        return "--"
    if pd.isna(x):
        return "--"
    if abs(x) < 0.005 and x != 0:
        return f"{x:.4f}"
    return f"{x:.{decimals}f}"


def fmt_tau(t):
    if t == int(t):
        return f"{int(t)}"
    return f"{t:g}"


def find_row_for_tau(sweep, tau):
    matches = sweep[abs(sweep["threshold"] - tau) < 1e-9]
    if matches.empty:
        return None
    return matches.iloc[0]


def build_summary_table(runs, use_siunitx):
    """runs: OrderedDict[label -> (summary, sweep)]."""
    lines = []
    lines.append(r"% Auto-generated by tools/firing_percent_latex_tables.py")
    lines.append(r"% Self-contained tabular; paste inside your own \begin{table}...\end{table}.")
    lines.append(r"\begin{tabular}{l r r r r r r r}")
    lines.append(r"\toprule")
    header = (r"Scope / mode & N regions & Avg firing & Rec.\ $\tau$ & "
              + r" & ".join(BUCKET_HEADERS) + r" \\")
    sub = r" &  & rate (\%) &  & " + r" & ".join([r"(\%)"] * 4) + r" \\"
    lines.append(header)
    lines.append(sub)
    lines.append(r"\midrule")

    for label, (summary, sweep) in runs.items():
        rec_tau = float(summary.get("recommended_tau", float("nan")))
        avg_rate_pct = 100.0 * float(summary.get("avg_firing_rate", float("nan")))
        n_points = int(summary.get("n_points", 0))

        rec_row = find_row_for_tau(sweep, rec_tau)
        if rec_row is None:
            bucket_cells = ["--"] * 4
        else:
            bucket_cells = [fmt_pct(float(rec_row[c])) for c in BUCKET_COLUMNS]

        cells = [
            label,
            fmt_int(n_points, use_siunitx),
            fmt_pct(avg_rate_pct),
            fmt_tau(rec_tau),
            *bucket_cells,
        ]
        lines.append(" & ".join(cells) + r" \\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    return "\n".join(lines) + "\n"


def build_sweep_table(runs, tau_subset, use_siunitx):
    n_modes = len(runs)
    cols = "l " + " ".join(["r r r r"] * n_modes)
    lines = []
    lines.append(r"% Auto-generated by tools/firing_percent_latex_tables.py")
    lines.append(r"% Self-contained tabular; paste inside your own \begin{table}...\end{table}.")
    lines.append(rf"\begin{{tabular}}{{{cols}}}")
    lines.append(r"\toprule")

    # Top-level header: blank first cell, then each label spans 4 cols
    top = [r"$\tau$"]
    for label in runs.keys():
        top.append(rf"\multicolumn{{4}}{{c}}{{{label}}}")
    lines.append(" & ".join(top) + r" \\")

    # \cmidrule under each group
    cmidrules = []
    col_start = 2
    for _ in runs.keys():
        cmidrules.append(rf"\cmidrule(lr){{{col_start}-{col_start + 3}}}")
        col_start += 4
    lines.append(" ".join(cmidrules))

    # Sub-header: % points >=1, >=2, >=5, >=10 for each group
    sub = [""]
    for _ in runs.keys():
        sub.extend(BUCKET_HEADERS)
    lines.append(" & ".join(sub) + r" \\")
    lines.append(r"\midrule")

    for tau in tau_subset:
        row = [fmt_tau(tau)]
        for label, (_, sweep) in runs.items():
            r = find_row_for_tau(sweep, tau)
            if r is None:
                row.extend(["--"] * 4)
            else:
                row.extend(fmt_pct(float(r[c])) for c in BUCKET_COLUMNS)
        lines.append(" & ".join(row) + r" \\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    return "\n".join(lines) + "\n"


def main():
    args = parse_args()
    setup_logging(args.log_level)

    inputs = parse_inputs(args.inputs)
    if not inputs:
        logger.error("No inputs provided")
        sys.exit(2)

    tau_subset = [float(x) for x in args.tau_subset.split(",")]

    runs = OrderedDict()
    for label, path in inputs.items():
        logger.info(f"Loading {label} from {path}")
        runs[label] = load_run(path)

    os.makedirs(args.output_dir, exist_ok=True)

    summary_tex = build_summary_table(runs, args.use_siunitx)
    sweep_tex = build_sweep_table(runs, tau_subset, args.use_siunitx)

    summary_out = os.path.join(args.output_dir, "summary_table.tex")
    sweep_out = os.path.join(args.output_dir, "sweep_table.tex")
    with open(summary_out, "w") as f:
        f.write(summary_tex)
    with open(sweep_out, "w") as f:
        f.write(sweep_tex)

    logger.info(f"Wrote: {summary_out}")
    logger.info(f"Wrote: {sweep_out}")
    print(summary_tex)
    print(sweep_tex)


if __name__ == "__main__":
    main()
